import { addSnapshotRemarkAction } from "@/app/actions/portal";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { mediaImages } from "@/lib/portal/media-client";
import { relativeTime } from "@/lib/portal/utils";

function safeHttpUrl(value: unknown): string | null {
  const raw = String(value ?? "").trim();
  if (!raw) return null;
  try {
    const url = new URL(raw);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    return url.toString();
  } catch {
    return null;
  }
}

export type SnapshotRemark = {
  id: string;
  body: string;
  created_at: string;
  author_id?: string | null;
  resolved?: boolean | null;
  profiles?: {
    full_name?: string | null;
    email?: string | null;
    role?: string | null;
  } | null;
};

/** Shared progress card for admin + client — shows screenshots, not broken links. */
export function ProgressUpdateCard({
  snapshotId,
  title,
  changelog,
  createdAt,
  publishedAt,
  stagingUrl,
  media,
  autoGenerated,
  remarks = [],
  canComment = false,
}: {
  snapshotId?: string;
  title: string;
  changelog?: string | null;
  createdAt?: string | null;
  publishedAt?: string | null;
  stagingUrl?: string | null;
  media?: unknown;
  autoGenerated?: boolean;
  remarks?: SnapshotRemark[];
  /** When true, show a comment form under the update. */
  canComment?: boolean;
}) {
  const images = mediaImages(media);
  const preview = safeHttpUrl(stagingUrl);
  const when = relativeTime(String(publishedAt ?? createdAt ?? ""));
  const sortedRemarks = [...remarks].sort(
    (a, b) =>
      new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
  );

  return (
    <article className="overflow-hidden rounded-lg border border-[#24302b]">
      {images[0] ? (
        <div className="border-b border-[#24302b] bg-[#0d1411]">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={images[0].url}
            alt={title}
            className="max-h-80 w-full object-cover object-top"
          />
        </div>
      ) : null}
      <div className="space-y-2 px-3 py-3">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <p className="text-sm font-medium">
            {title}
            {autoGenerated ? (
              <span className="ml-2 font-mono text-[10px] text-[#b08d1f]">
                daily
              </span>
            ) : null}
          </p>
          {when ? (
            <span className="font-mono text-[11px] text-[#5f6f68]">{when}</span>
          ) : null}
        </div>
        {changelog ? (
          <p className="text-sm whitespace-pre-wrap text-[#9aaba2]">
            {changelog}
          </p>
        ) : null}
        {images.length > 1 ? (
          <div className="flex flex-wrap gap-2 pt-1">
            {images.slice(1).map((image) => (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                key={image.url}
                src={image.url}
                alt=""
                className="h-16 w-24 rounded object-cover"
              />
            ))}
          </div>
        ) : null}
        {preview ? (
          <a
            href={preview}
            target="_blank"
            rel="noreferrer"
            className="inline-flex font-mono text-xs text-[#d4b45a] underline-offset-4 hover:underline"
          >
            Open live preview
          </a>
        ) : null}

        {sortedRemarks.length > 0 ? (
          <div className="space-y-2 border-t border-[#24302b] pt-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#9aaba2]">
              Feedback
            </p>
            <ul className="space-y-2">
              {sortedRemarks.map((remark) => {
                const author = remark.profiles;
                const staff =
                  author?.role === "SUPER_ADMIN" ||
                  author?.role === "ADMIN" ||
                  author?.role === "STAFF";
                return (
                  <li
                    key={remark.id}
                    className="rounded-md border border-[#2a3832] bg-[#0f1613] px-2.5 py-2"
                  >
                    <p className="font-mono text-[11px] text-[#9aaba2]">
                      <span
                        className={
                          staff ? "text-[#d4b45a]" : "text-[#c8d3cd]"
                        }
                      >
                        {staff
                          ? author?.full_name || "Lynx team"
                          : author?.full_name || author?.email || "Client"}
                      </span>
                      <span className="text-[#5f6f68]">
                        {" "}
                        · {relativeTime(remark.created_at)}
                      </span>
                    </p>
                    <p className="mt-1 text-sm whitespace-pre-wrap text-[#e8eee9]">
                      {remark.body}
                    </p>
                  </li>
                );
              })}
            </ul>
          </div>
        ) : null}

        {canComment && snapshotId ? (
          <form
            action={addSnapshotRemarkAction}
            className="space-y-2 border-t border-[#24302b] pt-3"
          >
            <input type="hidden" name="snapshotId" value={snapshotId} />
            <label
              htmlFor={`remark-${snapshotId}`}
              className="block font-mono text-[10px] uppercase tracking-[0.16em] text-[#9aaba2]"
            >
              Something look off?
            </label>
            <Textarea
              id={`remark-${snapshotId}`}
              name="body"
              rows={3}
              required
              placeholder="Tell us what looks wrong, missing, or needs a tweak…"
              className="border-[#24302b] bg-[#0f1613]"
            />
            <Button type="submit" size="sm" variant="outline">
              Leave feedback
            </Button>
          </form>
        ) : null}
      </div>
    </article>
  );
}
